language: r
sudo: required
dist: trusty
warnings_are_errors: true
 
r:
  - oldrel
  - release
  - devel
 
r_packages:
  - devtools
  
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls(quiet = FALSE)'

notifications:
  email:
    recipients:
      -laabs@imbs.uni-luebeck.de 
    on_success: change
    on_failure: change
